#ifndef LMORPHO_VERSION_H_
#define LMORPHO_VERSION_H_

#define LMORPHO_VERSION_MAJOR 0
#define LMORPHO_VERSION_MINOR 1
#define LMORPHO_VERSION_DEV dev

/* Convert above into verfion string */

#define LMORPHO_STRINGIFY2_(x) #x
#define LMORPHO_STRINGIFY_(x) LMORPHO_STRINGIFY2_(x)

#ifdef LMORPHO_VERSION_DEV
#define LMORPHO_VERSION LMORPHO_STRINGIFY_(LMORPHO_VERSION_MAJOR) "." LMORPHO_STRINGIFY_(LMORPHO_VERSION_MINOR) "-" LMORPHO_STRINGIFY_(LMORPHO_VERSION_DEV)
#else
#define LMORPHO_VERSION LMORPHO_STRINGIFY_(LMORPHO_VERSION_MAJOR) "." LMORPHO_STRINGIFY_(LMORPHO_VERSION_MINOR)
#endif

#endif // ndef LMORPHO_VERSION_H_
